name: CF CLI Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./mvnw clean package
  deploy:
    runs-on: self-hosted
    needs: build
    environment: trial
    steps:
      - run: |
          sed -i "s/\$ARTIFACT_NAME/$(find ./target -maxdepth 1 -type f -name "*.jar" | grep -o '[^/]*\.jar$')/" manifest.yml
      - uses: Ouroborosi/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push -f manifest.yml